#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

commit_msg=$(cat "$1")
merge_pattern="^Merge.+"
pattern="^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}"

# 병합 커밋 메시지 확인
if echo "$commit_msg" | grep -qE "$merge_pattern"; then
  exit 0
fi

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "커밋 메시지 제목이 올바르지 않습니다"
  echo "아래와 같은 형태로 작성 해 주세요"
  echo "feat(캐릭터): 테스트 기능 구현 완성"
  exit 1
fi
